# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1012, 74)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
        widget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.select_camera_button = QtWidgets.QRadioButton(self.groupBox_2)
        self.select_camera_button.setObjectName("select_camera_button")
        self.horizontalLayout_3.addWidget(self.select_camera_button)
        self.task_label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_label.sizePolicy().hasHeightForWidth())
        self.task_label.setSizePolicy(sizePolicy)
        self.task_label.setObjectName("task_label")
        self.horizontalLayout_3.addWidget(self.task_label)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.download_files = QtWidgets.QPushButton(widget)
        self.download_files.setObjectName("download_files")
        self.horizontalLayout.addWidget(self.download_files)
        self.groupBox = QtWidgets.QGroupBox(widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.task_options = QtWidgets.QComboBox(self.groupBox)
        self.task_options.setObjectName("task_options")
        self.task_options.addItem("")
        self.task_options.addItem("")
        self.task_options.addItem("")
        self.task_options.addItem("")
        self.horizontalLayout_2.addWidget(self.task_options)
        self.send_task = QtWidgets.QPushButton(self.groupBox)
        self.send_task.setObjectName("send_task")
        self.horizontalLayout_2.addWidget(self.send_task)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.groupBox_2.setTitle(_translate("widget", "Camera Info"))
        self.select_camera_button.setText(_translate("widget", "IP"))
        self.task_label.setText(_translate("widget", "Current Task:"))
        self.download_files.setText(_translate("widget", "Download Files"))
        self.groupBox.setTitle(_translate("widget", "Set Camera Task"))
        self.task_options.setItemText(0, _translate("widget", "Standby"))
        self.task_options.setItemText(1, _translate("widget", "Night Watch"))
        self.task_options.setItemText(2, _translate("widget", "Watch For Motion"))
        self.task_options.setItemText(3, _translate("widget", "Timelapse"))
        self.send_task.setText(_translate("widget", "Send Task"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
