# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timelaspe_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 221)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.verticalLayout.addWidget(self.dateTimeEdit_start)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dateTimeEdit_2_end = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_2_end.setObjectName("dateTimeEdit_2_end")
        self.verticalLayout.addWidget(self.dateTimeEdit_2_end)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_length = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_length.setObjectName("lineEdit_length")
        self.verticalLayout.addWidget(self.lineEdit_length)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox_fps = QtWidgets.QComboBox(Dialog)
        self.comboBox_fps.setObjectName("comboBox_fps")
        self.comboBox_fps.addItem("")
        self.comboBox_fps.addItem("")
        self.comboBox_fps.addItem("")
        self.comboBox_fps.addItem("")
        self.comboBox_fps.addItem("")
        self.verticalLayout.addWidget(self.comboBox_fps)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Start Date / Time"))
        self.label_2.setText(_translate("Dialog", "End Date / Time"))
        self.label_3.setText(_translate("Dialog", "Video Length in seconds"))
        self.label_4.setText(_translate("Dialog", "Frames Per Second"))
        self.comboBox_fps.setItemText(0, _translate("Dialog", "12"))
        self.comboBox_fps.setItemText(1, _translate("Dialog", "24"))
        self.comboBox_fps.setItemText(2, _translate("Dialog", "30"))
        self.comboBox_fps.setItemText(3, _translate("Dialog", "48"))
        self.comboBox_fps.setItemText(4, _translate("Dialog", "60"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
